# print('Please enter the following:          ')
# adjective = input('An Adjective:            ')
# animal = input('An Animal:                  ')
# verb1 = input('A Verb:                      ')
# exclamation = input('An Adjective:          ')
# verb2 = input('A Verb:                      ')
# verb3 = input('A Verb:                      ')
# print('While I was at the zoo I saw a {0} looking big old {1} in his cage {2} with a hat on his head and I said {3}'.format(adjective, animal, verb1,exclamation))
# print('that looks like my hat and I {0} at him and then {1} away on my bike'.format(verb2, verb3))