print('Please enter the following:')
adjective = input('An Adjective:                ')
animal =    input('An Animal:                   ')
verb1 =     input('A Verb:                      ')
exclamation = input('An Exclamation:            ')
verb2 = input('A Verb:                           ')
verb3 = input('A Verb                            ')
print('The other day, I was really in trouble. It all started when I saw a very {0} {1} {2} down the hallway. "{3}!" I yelled. But all I could think to do was to'.format(adjective, animal, verb1, exclamation.capitalize()))
print('{0} over and over. Miraculously, that caused it to stop, but not before it tried to {1} right in front of my family.'.format(verb2, verb3))
