print()
childs_meal = input('The cost of a childs meal?    ')
adults_meal = input('The cost of adults meal?     '     ')
children = input('How many children are there?      ')
adults = input('How many adults are there?     ')
print()

print(float({childs_meal} * int({children}))
# area_rectangle = (float(length_rectangle) * float(width_rectangle))
# print(F'The area of the square is {area_square}     ')
# print(f'The area of the rectangle is {area_rectangle}     ')
# radius_circle = input('What is the radius of the circle?     ')
# area_circle = ((float(radius_circle) * float(radius_circle)) * float(3.14))
# print(f'The area of the circle is {area_circle}     ')
# print()