# print()
# length_square = input('What is the length of the side the square?    ')
# length_rectangle = input('What is the length of the rectangle?     ')
# width_rectangle = input('What is the width of the rectangle      ')
# area_square = (float(length_square) * float(length_square))
# area_rectangle = (float(length_rectangle) * float(width_rectangle))
# print(F'The area of the square is {area_square}     ')
# print(f'The area of the rectangle is {area_rectangle}     ')
# radius_circle = input('What is the radius of the circle?     ')
# area_circle = ((float(radius_circle) * float(radius_circle)) * float(3.14))
# print(f'The area of the circle is {area_circle}     ')
# print()
#Stretch Activity
area_squarecm = float(area_squarecm/100) 
print(f'The area of the square is {area_squarecm} cm^2')
area_rectanglecm = float(area_rectangle/100)
print(f'The area of the rectangle is: {area_rectanglecm} cm^2')
area_circlecm = float(area_circle/100)
print(f'The area of a circle is: {area_circlecm} cm^2')
print()